name: CI

on:
  pull_request:
    branches:
      - dev
      - hom
      - prod

jobs:
runs-on: ubuntu-latest
		steps:
	 		-	name: Checkout	
				uses: actions/checkout@v4.2.0

	 		-	name: Docker Login
  			uses: docker/login-action@v3.3.0
  			with:
    			username: ${{ secrets.DOCKER_USERNAME }}
    			password: ${{ secrets.DOCKER_PASSWORD }}
  
    
